### Task List Schema
GET http://127.0.0.1:8000/api/task/schema/?format=json HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

### Task List - GET
GET http://127.0.0.1:8000/api/task/ HTTP/1.1
Authorization: ApiKey pavan:4b285cef0a606f159da59bf8b826e68460bcd6a2


### Task List - GET
GET http://127.0.0.1:8000/api/task/ HTTP/1.1
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

# Authorization: ApiKey tyrion:61de36c3e42b82d2b8ef33d74f86a3652f0ac417

### Task List - POST
POST http://127.0.0.1:8000/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

{
    "title":"Dinner",
    "description":"Biryani.."  
}

### Task List - PUT
PUT http://127.0.0.1:8000/api/task/17/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

{
    "title":"Who's awesomee?"  
}

### Task List - PUT
PUT http://127.0.0.1:8000/api/task/15/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey pavan:4b285cef0a606f159da59bf8b826e68460bcd6a2

{
    "description":"Biryani's bad."  
}

### Task List - DELETE
DELETE http://127.0.0.1:8000/api/task/16/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669


### Task List - DELETE
DELETE http://127.0.0.1:8000/api/task/15/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey pavan:4b285cef0a606f159da59bf8b826e68460bcd6a2

### User List - GET Schema
GET http://127.0.0.1:8000/api/user/schema/?format=json HTTP/1.1
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

### User List - GET with filter
GET http://127.0.0.1:8000/api/user/?format=json&username=tyrion HTTP/1.1
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

### Register Schema
GET http://127.0.0.1:8000/api/register/schema/?format=json HTTP/1.1
Content-Type: application/json

### Register
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username":"falak",
    "password":"Pavan@123"
}

### Login Schema
GET http://127.0.0.1:8000/api/login/schema/?format=json HTTP/1.1
Content-Type: application/json


### Login
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"falak",
    "password":"Pavan@123"
}

### FriendRequest Schema
GET http://127.0.0.1:8000/api/friend/schema/?format=json HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

### FriendRequest - GET
GET http://127.0.0.1:8000/api/friend/ HTTP/1.1
Authorization: ApiKey falak:45b2ac2079778fd395fa8aa31ce0653b58d8a4f1

### FriendRequest - GET
GET http://127.0.0.1:8000/api/friend/ HTTP/1.1
Authorization: ApiKey pavan:4b285cef0a606f159da59bf8b826e68460bcd6a2