### Task List

GET http://127.0.0.1:8000/api/task/schema/?format=json HTTP/1.1

### Register Schema

GET http://127.0.0.1:8000/api/register/schema/?format=json HTTP/1.1
Content-Type: application/json

### Register
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username":"tyrion",
    "password":"Anas@123"
}

### Login Schema
GET http://127.0.0.1:8000/api/login/schema/?format=json HTTP/1.1
Content-Type: application/json


### Login
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"tyrion",
    "password":"Anas@123"
}