### Task List Schema
GET http://127.0.0.1:8000/api/task/schema/?format=json HTTP/1.1
Authorization: ApiKey tyrion:61de36c3e42b82d2b8ef33d74f86a3652f0ac417

### Task List - GET
GET http://127.0.0.1:8000/api/task/ HTTP/1.1
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

# Authorization: ApiKey tyrion:61de36c3e42b82d2b8ef33d74f86a3652f0ac417

### Task List - POST
POST http://127.0.0.1:8000/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:6284ad0f9d76354cc209e61d8afab09c18ce6669

{
    "title":"Breakfast",
    "desctiption":"Yummyy.."
    
}

### Register Schema
GET http://127.0.0.1:8000/api/register/schema/?format=json HTTP/1.1
Content-Type: application/json

### Register
POST http://127.0.0.1:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username":"arya",
    "password":"Anas@123"
}

### Login Schema
GET http://127.0.0.1:8000/api/login/schema/?format=json HTTP/1.1
Content-Type: application/json


### Login
POST http://127.0.0.1:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"arya",
    "password":"Anas@123"
}