### Task List - GET All task 
GET http://127.0.0.1:8000/api/task/ HTTP/1.1
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

### Task List - GET All task I'm assigned to
GET http://127.0.0.1:8000/api/task/?assigned_to__username=anas HTTP/1.1
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

### Task List - GET - Filtering by creator
GET http://127.0.0.1:8000/api/task/?creator__username=arya HTTP/1.1
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

### Task List - GET particular task <id>
GET http://127.0.0.1:8000/api/task/2/ HTTP/1.1
Authorization: ApiKey falak:9ff0f1a1a03302ed670a22c7a81a1eac50012353

### Task List - POST
POST http://127.0.0.1:8000/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey anas:6a504cc86160b4c138e47816e6dd25b59ce4c841

{
    "title":"Task 1",
    "description":"new task"  
}

### Task List - POST
POST http://127.0.0.1:8000/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

{
    "title":"AOT",
    "description":"Masterpiece"  
}

### Task List - PUT
PUT http://127.0.0.1:8000/api/task/17/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

{
    "title":"Who's awesomee?"  
}

### Task List - PUT
PUT http://127.0.0.1:8000/api/task/2/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey falak:9ff0f1a1a03302ed670a22c7a81a1eac50012353

{
    "title":"Shingeki no kyojin"  
}

### Task List - DELETE
DELETE http://127.0.0.1:8000/api/task/2/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey arya:09cf641edad3619ace2cd606391332123502eef6

### Task List - DELETE
DELETE http://127.0.0.1:8000/api/task/2/ HTTP/1.1
Content-Type: application/json
Authorization: ApiKey falak:9ff0f1a1a03302ed670a22c7a81a1eac50012353
