# Generated by Django 4.0.1 on 2022-02-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='reciever',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='taskapp.profile'),
            preserve_default=False,
        ),
    ]
