# Generated by Django 4.0.1 on 2022-02-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_remove_friendrequest_reciever_friendrequest_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='updated',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created',
            new_name='updated_at',
        ),
    ]
