# Generated by Django 4.0.1 on 2022-02-02 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_alter_friendrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 2, 11, 29, 28, 884832, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
