# Generated by Django 4.0.1 on 2022-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_alter_friendrequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Completed', 'Completed')], default='Moderate', max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Completed', 'Completed')], default='Pending', max_length=12),
        ),
    ]
