# Generated by Django 4.0.1 on 2022-02-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_remove_task_progress_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Moderate', 'Moderate'), ('Urgent', 'Urgent')], default='Moderate', max_length=12),
        ),
    ]
